// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FlightBoard: typeof import('./src/components/flight/board.vue')['default']
    FlightDetails: typeof import('./src/components/flight/details.vue')['default']
    FlightList: typeof import('./src/components/flight/list.vue')['default']
    FlightListItem: typeof import('./src/components/flight/list-item.vue')['default']
    MainAlert: typeof import('./src/components/main/alert.vue')['default']
  }
}

export {}
